// 农资商品数据
const PRODUCTS = [
  {
    id: '1',
    name: '10%吡虫啉可湿性粉剂 500g 棉花蚜虫专用杀虫剂',
    spec: '500g/袋',
    price: 45,
    origPrice: 55,
    unit: '袋',
    icon: '🧪',
    imgBg: 'linear-gradient(135deg,#00BCD4,#0097A7)',
    hot: true,
    isNew: false,
    sold: 2380,
    rating: 4.9,
    store: '丰禾农资旗舰店',
    storeVerified: true,
    discount: '满200减30',
    cat: '农药'
  },
  {
    id: '2',
    name: '新陆早57号棉花种子 5kg装',
    spec: '5kg/袋',
    price: 128,
    origPrice: 148,
    unit: '袋',
    icon: '🌱',
    imgBg: 'linear-gradient(135deg,#66BB6A,#388E3C)',
    hot: false,
    isNew: true,
    sold: 1580,
    rating: 4.8,
    store: '新疆金丰种业',
    storeVerified: true,
    discount: '满500减50',
    cat: '种子'
  },
  {
    id: '3',
    name: '棉花专用复合肥 50kg 高钾型',
    spec: '50kg/袋',
    price: 180,
    origPrice: 210,
    unit: '袋',
    icon: '🌿',
    imgBg: 'linear-gradient(135deg,#8D6E63,#4E342E)',
    hot: true,
    isNew: false,
    sold: 892,
    rating: 4.7,
    store: '丰禾农资旗舰店',
    storeVerified: true,
    discount: '满200减30',
    cat: '化肥'
  },
  {
    id: '4',
    name: '地膜（白色）宽120cm 厚0.01mm 2000m/卷',
    spec: '120cm×2000m',
    price: 42,
    origPrice: 50,
    unit: '卷',
    icon: '📦',
    imgBg: 'linear-gradient(135deg,#CE93D8,#9C27B0)',
    hot: false,
    isNew: false,
    sold: 445,
    rating: 4.6,
    store: '喀什农膜直供',
    storeVerified: false,
    discount: '',
    cat: '地膜'
  },
  {
    id: '5',
    name: '滴灌带 16mm 壁厚0.2mm 100m/卷',
    spec: '100m/卷',
    price: 58,
    origPrice: 68,
    unit: '卷',
    icon: '💧',
    imgBg: 'linear-gradient(135deg,#4FC3F7,#0288D1)',
    hot: false,
    isNew: false,
    sold: 326,
    rating: 4.5,
    store: '疏附节水灌溉',
    storeVerified: false,
    discount: '',
    cat: '滴灌带'
  },
  {
    id: '6',
    name: '3%吡虫啉乳油 250ml 棉花专用杀虫剂',
    spec: '250ml/瓶',
    price: 38,
    origPrice: 45,
    unit: '瓶',
    icon: '🧴',
    imgBg: 'linear-gradient(135deg,#FF8A65,#E64A19)',
    hot: false,
    isNew: false,
    sold: 1820,
    rating: 4.8,
    store: '丰禾农资旗舰店',
    storeVerified: true,
    discount: '满200减30',
    cat: '农药'
  },
  {
    id: '7',
    name: '棉花脱叶催熟剂 乙烯利 250ml',
    spec: '250ml/瓶',
    price: 65,
    origPrice: 78,
    unit: '瓶',
    icon: '🍂',
    imgBg: 'linear-gradient(135deg,#FFCC80,#FB8C00)',
    hot: false,
    isNew: false,
    sold: 660,
    rating: 4.7,
    store: '丰禾农资旗舰店',
    storeVerified: true,
    discount: '满200减30',
    cat: '农药'
  },
  {
    id: '8',
    name: '棉花缩节胺 95% 可湿性粉剂 100g/袋',
    spec: '100g/袋',
    price: 28,
    origPrice: 35,
    unit: '袋',
    icon: '🔬',
    imgBg: 'linear-gradient(135deg,#B0BEC5,#546E7A)',
    hot: false,
    isNew: false,
    sold: 1230,
    rating: 4.6,
    store: '新疆金丰种业',
    storeVerified: true,
    discount: '满500减50',
    cat: '农药'
  }
]

const CATS = [
  { name: '全部', icon: '🛒', bg: '#FFF3E0' },
  { name: '种子', icon: '🌱', bg: '#E8F5E9' },
  { name: '化肥', icon: '🌿', bg: '#E0F2F1' },
  { name: '农药', icon: '🧪', bg: '#FFF3E0' },
  { name: '地膜', icon: '📦', bg: '#F3E5F5' },
  { name: '滴灌带', icon: '💧', bg: '#E3F2FD' }
]

module.exports = { PRODUCTS, CATS }
