const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../../..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const index = read('cotton-app/server/index.js')
const route = read('cotton-app/server/routes/academy.js')
const migration = read('cotton-app/server/db/migrate_academy.js')
const dashboard = read('cotton-app/server/public/admin/dashboard.html')
const publicAdmin = read('cotton-community/public/knowledge/policy-admin.html')
const manager = read('cotton-community/public/knowledge/academy-admin.js')
const miniList = read('cotton-public/pages/academy/index.js')
const miniSeries = read('cotton-public/pages/academy/series.js')
const miniCourse = read('cotton-public/pages/academy/course.js')
const academyData = read('cotton-public/utils/academy-data.js')

assert(index.includes("app.use('/api/miniapp-academy'"), 'mini program academy API should be mounted in cotton-app')
assert(migration.includes('CREATE TABLE IF NOT EXISTS academy_courses'), 'academy course table is missing')
assert(migration.includes('CREATE TABLE IF NOT EXISTS academy_series') && migration.includes('series_key'), 'academy series or lesson assignment is missing')
assert(migration.includes('video_url'), 'VOD playback URL column is missing')
assert(route.includes('playbackUrl') && !route.includes('finderUserName'), 'VOD URL validation must replace channel-video fields')
assert(migration.includes('academy_progress') && migration.includes('academy_learning_points'), 'academy learning progress or points ledger is missing')
assert(!migration.includes('INSERT INTO academy_series') && !migration.includes('INSERT INTO academy_courses'), 'academy migration must not seed demo content')
assert(route.includes("router.get('/courses'") && route.includes("router.get('/courses/:courseId'"), 'public academy course APIs are incomplete')
assert(route.includes("router.get('/series'") && route.includes("router.get('/series/:seriesKey'"), 'public academy series APIs are incomplete')
assert(route.includes("router.post('/admin/series'") && route.includes("router.put('/admin/series/:id'") && route.includes("router.delete('/admin/series/:id'"), 'academy series management APIs are incomplete')
assert(route.includes("router.post('/admin/courses'") && route.includes("router.put('/admin/courses/:id'"), 'academy course management APIs are incomplete')
assert(route.includes("router.get('/learning'") && route.includes('academy_learning_points') && route.includes('LEARNING_POINTS'), 'learning center or points awarding API is incomplete')
assert(!dashboard.includes('data-panel="academy"'), 'academy module should not be added to the commerce website admin')
assert(publicAdmin.includes('data-view="academy"') && publicAdmin.includes('id="academyPanel"'), 'academy navigation or panel is missing from public-service admin')
assert(manager.includes('saveSeries') && manager.includes('academySeriesTable'), 'academy series manager is missing')
assert(!manager.includes('uploadVideoToVod') && !publicAdmin.includes('uploadAcademyVideoBtn'), 'academy admin should not provide a video upload button')
assert(publicAdmin.includes('academyVideoUrl') && !publicAdmin.includes('academyFeedId'), 'admin must accept VOD playback URLs')
assert(route.includes('payload.is_community_admin') && route.includes('community_admins'), 'public-service administrators should be able to manage academy courses')
assert(miniList.includes('/api/miniapp-academy/series') && miniList.includes('switchLevel'), 'mini program academy series list or level tabs are incomplete')
assert(miniSeries.includes('/api/miniapp-academy/series/') && miniSeries.includes('openLesson'), 'mini program series directory is not connected')
assert(miniCourse.includes('/api/miniapp-academy') && miniCourse.includes('loadCourse'), 'mini program course detail is not driven by admin data')
assert(miniCourse.includes('openDirectory'), 'course player should link back to its series directory')
assert(read('cotton-public/pages/academy/course.wxml').includes('<video'), 'course player should use VOD video')
assert(!read('cotton-public/pages/academy/course.wxml').includes('<channel-video'), 'legacy Video Accounts player must not remain')
assert(!manager.includes('academyFeedToken') && !manager.includes('academyFeedId'), 'legacy Video Accounts fields must not remain in academy admin')
assert(academyData.includes('const COURSES = []') && academyData.includes('const SERIES = []'), 'mini program must not include fallback demo courses')

console.log('academy management tests passed')
