const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../../..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const index = read('cotton-app/server/index.js')
const route = read('cotton-app/server/routes/academy.js')
const migration = read('cotton-app/server/db/migrate_academy.js')
const dashboard = read('cotton-app/server/public/admin/dashboard.html')
const publicAdmin = read('cotton-community/public/knowledge/policy-admin.html')
const manager = read('cotton-community/public/knowledge/academy-admin.js')
const miniList = read('cotton-public/pages/academy/index.js')
const miniSeries = read('cotton-public/pages/academy/series.js')
const miniCourse = read('cotton-public/pages/academy/course.js')
const academyData = read('cotton-public/utils/academy-data.js')

assert(index.includes("app.use('/api/miniapp-academy'"), 'mini program academy API should be mounted in cotton-app')
assert(migration.includes('CREATE TABLE IF NOT EXISTS academy_courses'), 'academy course table is missing')
assert(migration.includes('CREATE TABLE IF NOT EXISTS academy_series') && migration.includes('series_key'), 'academy series or lesson assignment is missing')
assert(migration.includes('vod_file_id') && migration.includes('vod_status'), 'VOD media fields are missing')
assert(!migration.includes('INSERT INTO academy_series') && !migration.includes('INSERT INTO academy_courses'), 'academy migration must not seed demo content')
assert(route.includes("router.get('/courses'") && route.includes("router.get('/courses/:courseId'"), 'public academy course APIs are incomplete')
assert(route.includes("router.get('/series'") && route.includes("router.get('/series/:seriesKey'"), 'public academy series APIs are incomplete')
assert(route.includes("router.post('/admin/upload-signature'") && route.includes('vodUploadSignature'), 'VOD upload signature endpoint is missing')
assert(route.includes("router.post('/admin/courses'") && route.includes("router.put('/admin/courses/:id'"), 'academy course management APIs are incomplete')
assert(!dashboard.includes('data-panel="academy"'), 'academy module should not be added to the commerce website admin')
assert(publicAdmin.includes('data-view="academy"') && publicAdmin.includes('id="academyPanel"'), 'academy navigation or panel is missing from public-service admin')
assert(manager.includes('createVodClient') && manager.includes('uploadVideoToVod'), 'academy VOD uploader is missing')
assert(publicAdmin.includes('vod-js-sdk-v6') && publicAdmin.includes('academyVodFileId'), 'VOD browser SDK or FileId field is missing')
assert(route.includes('payload.is_community_admin') && route.includes('community_admins'), 'public-service administrators should be able to manage academy courses')
assert(miniList.includes('/api/miniapp-academy/series') && miniList.includes('switchLevel'), 'mini program academy series list or level tabs are incomplete')
assert(miniSeries.includes('/api/miniapp-academy/series/') && miniSeries.includes('openLesson'), 'mini program series directory is not connected')
assert(miniCourse.includes('/api/miniapp-academy') && miniCourse.includes('loadCourse'), 'mini program course detail is not driven by admin data')
assert(miniCourse.includes('openDirectory'), 'course player should link back to its series directory')
assert(academyData.includes('const COURSES = []') && academyData.includes('const SERIES = []'), 'mini program must not include fallback demo courses')

console.log('academy management tests passed')
