const assert = require('assert')
const fs = require('fs')
const path = require('path')

const serverDir = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(serverDir, file), 'utf8')

const index = read('index.js')
const login = read('public/admin/login.html')
const dashboard = read('public/admin/dashboard.html')
const packageJson = JSON.parse(read('package.json'))
const entrypoint = read('docker-entrypoint.sh')

assert(index.includes("app.get('/community'"), 'cotton-app should expose a public community redirect')
assert(index.includes("app.get('/community/public'"), 'cotton-app should expose the public-service platform redirect')
assert(index.includes("app.get('/community/business'"), 'cotton-app should expose the business platform redirect')
assert(!index.includes("app.get('/community/admin'"), 'cotton-app should not expose the removed admin community redirect')
assert(index.includes('COMMUNITY_BASE_URL'), 'community URL should be environment driven')
assert(index.includes("redirectCommunity('/public/')") && index.includes("redirectCommunity('/business/')"), 'platform redirects should use shared community redirect handling')
assert(index.includes('COMMUNITY_DIRECT_PORT'), 'direct local admin access should redirect from port 3000 to the community port')
assert(!index.includes("app.use('/knowledge'"), 'cotton-app must not serve community pages')
assert(!index.includes("app.use('/api/knowledge'"), 'cotton-app must not mount community APIs')
assert(login.includes('href="/community/public"'), 'platform login should link to public service')
assert(login.includes('href="/community/business"'), 'platform login should link to business service')
assert(!dashboard.includes("window.open('/community/public'"), 'admin dashboard should not expose the public platform')
assert(!dashboard.includes("window.open('/community/business'"), 'admin dashboard should not expose the business platform')
assert(!dashboard.includes("window.location.href='/community/admin'"), 'admin dashboard should not link to community operations')
assert(!packageJson.scripts['migrate:knowledge'], 'knowledge migrations belong to cotton-community')
assert(!packageJson.scripts.test.includes('knowledge-hall.test.js'), 'knowledge tests belong to cotton-community')
assert(!entrypoint.includes('migrate_knowledge_hall.js'), 'cotton-app startup must not mutate community tables')
assert(!fs.existsSync(path.join(serverDir, 'routes', 'knowledge.js')), 'community route must be removed from cotton-app')
assert(!fs.existsSync(path.join(serverDir, 'public', 'knowledge')), 'community static site must be removed from cotton-app')

console.log('community project boundary tests passed')
