const i18n = require('./i18n')

const COPY = {
  zh: {
    booking: { title:'预约农机',noPlot:'不指定地块',plot:'作业地块',address:'作业地址',map:'地图选点',addressPh:'地图选点或手动输入作业地点',date:'作业日期',area:'作业面积',areaPh:'请输入亩数',rentalDays:'租赁天数',daysPh:'请输入天数',days:'天',mu:'亩',phone:'联系电话',phonePh:'便于机手联系',note:'备注',notePh:'地块位置说明、特殊要求等',unitPrice:'单价',estimated:'预估总价',deposit:'需付定金（20%）',trust:'定金由平台托管；取消或拒单时真实付款原路退回',depositLabel:'定金',submitting:'提交中…',submit:'提交预约',needAddress:'请填写作业地址',needArea:'请填写正确的计费数量',needPhone:'请填写正确的11位联系电话',invalidDate:'作业日期不能早于今天',submitFail:'提交失败',network:'网络异常',location:'已选择位置',permission:'需要位置权限',permissionContent:'请在设置中允许使用位置，才能在地图上选择作业地点。',settings:'去设置',loadFail:'机具信息加载失败' },
    orders: { title:'我的农机预约',loading:'加载中…',empty:'暂无预约记录',noPlot:'不指定地块',mu:'亩',total:'总价',deposit:'定金',delete:'删除',view:'查看 ›',network:'网络异常',deleteTitle:'删除订单',deleteContent:'确定删除该订单记录吗？删除后不可恢复。',deleted:'已删除',deleteFail:'删除失败',awaitingPayment:'待付款',paidDeposit:'已付定金',paidFull:'已付清',refunded:'已退款',payNow:'继续付款',payBalance:'支付尾款' },
    detail: { title:'农机详情',rangeWarning:'您的位置超出可服务范围，农机手可能无法上门作业',deliver:'可服务',response:'响应',orders:'单',highlights:'规格亮点',params:'技术参数',service:'服务说明',reviews:'服务评价',overall:'综合',noReview:'暂无评价',anonymous:'匿名农户',timely:'及时',quality:'质量',attitude:'态度',price:'价格',reply:'农机手回复：',notFound:'机具不存在或已下架',contact:'联系农机手',book:'立即预约',unavailable:'暂不可预约',paymentPending:'农机手尚未开通微信收款',loadFail:'加载失败',network:'网络异常',noPhone:'暂无联系电话',loginTitle:'请先登录',loginContent:'预约农机需要先登录账号',goLogin:'去登录' },
    pay: { title:'微信支付',amount:'需支付金额',orderNo:'订单号',total:'作业总价',deposit:'定金（20%）',balance:'支付尾款',balanceSub:'作业已完成，支付剩余服务款',depositPay:'支付定金',recommend:'推荐',depositSub:'先付 20%，作业完成后付尾款',full:'支付全款',fullSub:'一次性付清',trust:'微信支付保障：款项支付至农机手特约商户，平台按审核通过的佣金比例分账。',paying:'支付中…',confirm:'确认支付',loadFail:'订单加载失败',unavailable:'微信支付暂不可用',syncFail:'支付状态同步失败',success:'支付成功',incomplete:'支付未完成' },
    track: { title:'订单跟踪',cancelled:'订单已取消',completed:'作业已完成，感谢使用',distance:'农机手距地块约',orderNo:'订单号',live:'农机手实时位置（15 秒更新）',base:'农机手基地位置（当前未共享实时定位）',about:'约',contact:'联系',plot:'作业地块',none:'不指定',address:'作业地址',area:'作业面积',rentalDays:'租赁天数',mu:'亩',date:'作业日期',period:'租赁日期',total:'作业总价',paid:'已支付',payStatus:'支付状态',paidFull:'已付清',paidDeposit:'已付定金',refunded:'已退款',unpaid:'未支付',refundStatus:'退款状态',refundProcessing:'退款处理中',refundFailed:'退款发起失败，请联系客服',balance:'支付尾款',payNow:'继续付款',awaitingPayment:'待付款',paymentDeadline:'付款截止',cancel:'取消预约',review:'去评价',reviewed:'已评价',contactOperator:'联系农机手',back:'返回',noPhone:'暂无联系电话',cancelTitle:'取消预约',cancelContent:'确定取消该预约吗？已支付款项将原路退回。',cancelledToast:'已取消',cancelFail:'取消失败',loadFail:'加载失败',network:'网络异常' },
    review: { title:'服务评价',content:'评价内容',placeholder:'说说这次作业的体验，帮助其他棉农参考…',submitting:'提交中…',submit:'提交评价',success:'评价成功',fail:'评价失败',network:'网络异常' }
  },
  ug: {
    booking: { title:'ماشىنا زاكاز قىلىش',noPlot:'يەر بەلگىلەنمىگەن',plot:'ئىشلەيدىغان يەر',address:'ئىش ئورنى',map:'خەرىتىدىن تاللاش',addressPh:'خەرىتىدىن تاللاڭ ياكى ئادرېس كىرگۈزۈڭ',date:'ئىش چېسلاسى',area:'ئىش كۆلىمى',areaPh:'مو سانىنى كىرگۈزۈڭ',rentalDays:'ئىجارە كۈنى',daysPh:'كۈن سانىنى كىرگۈزۈڭ',days:'كۈن',mu:'مو',phone:'ئالاقە تېلېفونى',phonePh:'ماشىنا ئىگىسى ئالاقىلىشىدۇ',note:'ئىزاھ',notePh:'يەر ئورنى ۋە ئالاھىدە تەلەپ',unitPrice:'بىرلىك باھا',estimated:'مۆلچەر ئومۇمىي باھا',deposit:'زەكالەت (20%)',trust:'زەكالەتنى سۇپا باشقۇرىدۇ؛ بىكار قىلىنسا ھەقىقىي پۇل ئەسلى يول بىلەن قايتىدۇ',depositLabel:'زەكالەت',submitting:'تاپشۇرۇۋاتىدۇ…',submit:'زاكاز تاپشۇرۇش',needAddress:'ئىش ئورنىنى تولدۇرۇڭ',needArea:'توغرا ھېسابلاش مىقدارىنى كىرگۈزۈڭ',needPhone:'توغرا تېلېفون نومۇرىنى كىرگۈزۈڭ',invalidDate:'ئىش چېسلاسى بۈگۈندىن بۇرۇن بولمايدۇ',submitFail:'تاپشۇرۇش مەغلۇپ',network:'تور نورمال ئەمەس',location:'ئورۇن تاللاندى',permission:'ئورۇن ھوقۇقى كېرەك',permissionContent:'خەرىتىدىن ئورۇن تاللاش ئۈچۈن تەڭشەكتە ئورۇن ھوقۇقىغا رۇخسەت قىلىڭ.',settings:'تەڭشەك',loadFail:'ماشىنا ئۇچۇرى يۈكلەنمىدى' },
    orders: { title:'ماشىنا زاكازلىرىم',loading:'يۈكلىنىۋاتىدۇ…',empty:'زاكاز خاتىرىسى يوق',noPlot:'يەر بەلگىلەنمىگەن',mu:'مو',total:'ئومۇمىي باھا',deposit:'زەكالەت',delete:'ئۆچۈرۈش',view:'كۆرۈش ›',network:'تور نورمال ئەمەس',deleteTitle:'زاكازنى ئۆچۈرۈش',deleteContent:'بۇ زاكاز خاتىرىسى ئۆچۈرۈلسۇنمۇ؟ قايتۇرغىلى بولمايدۇ.',deleted:'ئۆچۈرۈلدى',deleteFail:'ئۆچۈرۈش مەغلۇپ',awaitingPayment:'تۆلەشنى كۈتۈش',paidDeposit:'زەكالەت تۆلەندى',paidFull:'تولۇق تۆلەندى',refunded:'قايتۇرۇلدى',payNow:'داۋاملىق تۆلەش',payBalance:'قالدۇقنى تۆلەش' },
    detail: { title:'ماشىنا تەپسىلاتى',rangeWarning:'ئورنىڭىز مۇلازىمەت دائىرىسىدىن سىرت، ماشىنا يېتىپ بارالماسلىقى مۇمكىن',deliver:'مۇلازىمەت',response:'جاۋاب',orders:'زاكاز',highlights:'ئالاھىدىلىكى',params:'تېخنىكىلىق پارامېتىر',service:'مۇلازىمەت چۈشەندۈرۈشى',reviews:'مۇلازىمەت باھاسى',overall:'ئومۇمىي',noReview:'باھا يوق',anonymous:'نامسىز دېھقان',timely:'ۋاقىت',quality:'سۈپەت',attitude:'مۇئامىلە',price:'باھا',reply:'ماشىنا ئىگىسىنىڭ جاۋابى: ',notFound:'ماشىنا يوق ياكى چۈشۈرۈلگەن',contact:'ماشىنا ئىگىسى بىلەن ئالاقە',book:'ھازىر زاكاز',unavailable:'ھازىر زاكاز قىلغىلى بولمايدۇ',paymentPending:'ماشىنا ئىگىسى WeChat پۇل ئېلىشنى ئاچمىغان',loadFail:'يۈكلەش مەغلۇپ',network:'تور نورمال ئەمەس',noPhone:'تېلېفون يوق',loginTitle:'ئالدى بىلەن كىرىڭ',loginContent:'ماشىنا زاكاز قىلىش ئۈچۈن ھېساباتقا كىرىڭ',goLogin:'كىرىش' },
    pay: { title:'WeChat تۆلەش',amount:'تۆلەيدىغان پۇل',orderNo:'زاكاز نومۇرى',total:'ئىش ئومۇمىي باھاسى',deposit:'زەكالەت (20%)',balance:'قالدۇق پۇلنى تۆلەش',balanceSub:'ئىش تاماملاندى، قالغان مۇلازىمەت پۇلىنى تۆلەڭ',depositPay:'زەكالەت تۆلەش',recommend:'تەۋسىيە',depositSub:'ئالدى بىلەن 20%، ئىشتىن كېيىن قالدۇق پۇل',full:'تولۇق تۆلەش',fullSub:'بىر قېتىمدا تولۇق تۆلەش',trust:'WeChat تۆلەش كاپالىتى: پۇل ماشىنا ئىگىسىنىڭ ئالاھىدە سودىگەر ھېسابىغا تۆلىنىپ، تەستىقلانغان نىسبەتتە بۆلۈنىدۇ.',paying:'تۆلەۋاتىدۇ…',confirm:'تۆلەشنى جەزملەش',loadFail:'زاكاز يۈكلەنمىدى',unavailable:'WeChat تۆلەشنى ئىشلەتكىلى بولمايدۇ',syncFail:'تۆلەش ھالىتى ماسلاشمىدى',success:'تۆلەش مۇۋەپپەقىيەتلىك',incomplete:'تۆلەش تاماملانمىدى' },
    track: { title:'زاكاز ئىز قوغلاش',cancelled:'زاكاز بىكار قىلىندى',completed:'ئىش تاماملاندى، رەھمەت',distance:'ماشىنا بىلەن يەر ئارىلىقى تەخمىنەن',orderNo:'زاكاز نومۇرى',live:'ماشىنىنىڭ نەق مەيدان ئورنى (15 سېكۇنتتا يېڭىلىنىدۇ)',base:'ماشىنا بازىسى (نەق مەيدان ئورنى ھەمبەھىرلەنمىگەن)',about:'تەخمىنەن',contact:'ئالاقە',plot:'ئىش يېرى',none:'بەلگىلەنمىگەن',address:'ئىش ئورنى',area:'ئىش كۆلىمى',rentalDays:'ئىجارە كۈنى',mu:'مو',date:'ئىش چېسلاسى',period:'ئىجارە ۋاقتى',total:'ئومۇمىي باھا',paid:'تۆلەنگەن',payStatus:'تۆلەش ھالىتى',paidFull:'تولۇق تۆلەندى',paidDeposit:'زەكالەت تۆلەندى',refunded:'قايتۇرۇلدى',unpaid:'تۆلەنمىدى',refundStatus:'پۇل قايتۇرۇش ھالىتى',refundProcessing:'پۇل قايتۇرۇلۇۋاتىدۇ',refundFailed:'پۇل قايتۇرۇش باشلانمىدى، مۇلازىمەت بىلەن ئالاقىلىشىڭ',balance:'قالدۇق پۇلنى تۆلەش',payNow:'داۋاملىق تۆلەش',awaitingPayment:'تۆلەشنى كۈتۈش',paymentDeadline:'تۆلەش مۆھلىتى',cancel:'زاكازنى بىكار قىلىش',review:'باھا بېرىش',reviewed:'باھا بېرىلدى',contactOperator:'ماشىنا ئىگىسى بىلەن ئالاقە',back:'قايتىش',noPhone:'تېلېفون يوق',cancelTitle:'زاكازنى بىكار قىلىش',cancelContent:'زاكاز بىكار قىلىنسۇنمۇ؟ تۆلەنگەن پۇل ئەسلى يول بىلەن قايتىدۇ.',cancelledToast:'بىكار قىلىندى',cancelFail:'بىكار قىلىش مەغلۇپ',loadFail:'يۈكلەش مەغلۇپ',network:'تور نورمال ئەمەس' },
    review: { title:'مۇلازىمەت باھاسى',content:'باھا مەزمۇنى',placeholder:'بۇ قېتىملىق ئىش تەجرىبىڭىزنى يېزىڭ…',submitting:'تاپشۇرۇۋاتىدۇ…',submit:'باھا تاپشۇرۇش',success:'باھا مۇۋەپپەقىيەتلىك',fail:'باھا مەغلۇپ',network:'تور نورمال ئەمەس' }
  }
}

const STATUS = {
  zh: { pending:'待接单',accepted:'已接单',departed:'已出发',arrived:'已到场',working:'作业中',completed:'已完成',cancelled:'已取消' },
  ug: { pending:'قوبۇل قىلىشنى كۈتۈش',accepted:'قوبۇل قىلىندى',departed:'يولغا چىقتى',arrived:'يېتىپ كەلدى',working:'ئىشلەۋاتىدۇ',completed:'تاماملاندى',cancelled:'بىكار قىلىندى' }
}

function getCopy(page, lang = i18n.getLanguage()) {
  return COPY[lang === 'ug' ? 'ug' : 'zh'][page] || {}
}

function statusLabel(status, lang = i18n.getLanguage()) {
  return STATUS[lang === 'ug' ? 'ug' : 'zh'][status] || status
}

function orderTabs(lang = i18n.getLanguage()) {
  return lang === 'ug'
    ? [{key:'all',label:'ھەممىسى'},{key:'pending',label:'كۈتۈش'},{key:'ongoing',label:'ئىجرا'},{key:'completed',label:'تامام'},{key:'cancelled',label:'بىكار'}]
    : [{key:'all',label:'全部'},{key:'pending',label:'待接单'},{key:'ongoing',label:'进行中'},{key:'completed',label:'已完成'},{key:'cancelled',label:'已取消'}]
}

module.exports = { getCopy, statusLabel, orderTabs }
