const assert = require('assert')
const fs = require('fs')
const path = require('path')

const communityRoot = path.resolve(__dirname, '..')
const workspaceRoot = path.resolve(communityRoot, '..')
const read = relativePath => fs.readFileSync(path.join(workspaceRoot, relativePath), 'utf8')

const route = read('cotton-community/routes/academy.js')
const server = read('cotton-community/server.js')
const migration = read('cotton-community/db/migrate.js')
const nginx = read('deploy/nginx.conf')
const courseJs = read('cotton-public/pages/academy/course.js')
const courseWxml = read('cotton-public/pages/academy/course.wxml')
const courseData = read('cotton-public/utils/academy-data.js')
const academyIndex = read('cotton-public/pages/academy/index.wxml')
const seriesPage = read('cotton-public/pages/academy/series.wxml')

assert(server.includes("app.use('/api/academy'"), 'academy API is not mounted')
assert(nginx.includes('location ^~ /api/academy/'), 'academy API is not routed through Nginx')
assert(migration.includes('CREATE TABLE IF NOT EXISTS academy_comments') && migration.includes('CREATE TABLE IF NOT EXISTS academy_comment_likes'), 'academy comment tables are missing')
assert(route.includes("router.get('/courses/:courseId/comments'") && route.includes("router.post('/courses/:courseId/comments'") && route.includes("router.post('/courses/:courseId/comments/:commentId/like'"), 'academy comments, replies or likes API is incomplete')
assert(courseWxml.includes('autoplay="true"') && courseWxml.includes('class="comment-section"') && courseWxml.includes('class="comment-bar"'), 'course detail should autoplay configured videos and show a comment interface')
assert(academyIndex.includes('level-tabs') && academyIndex.includes('series-grid'), 'academy should show level tabs and series course cards')
assert(seriesPage.includes('课程目录') && seriesPage.includes('openLesson'), 'series page should show a clickable lesson directory')
assert(courseJs.includes('/api/academy/courses/') && courseJs.includes('submitComment') && courseJs.includes('toggleLike'), 'course page is not connected to shared comments')
assert((courseData.match(/duration: '(?:\d+秒|1分\d+秒)'/g) || []).length >= 15, 'video lessons should be approximately one minute long')

console.log('academy tests passed')
