const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const migrate = read('db/migrate.js')
const route = read('routes/daily-todos.js')
const server = read('server.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/todo-admin.js')
const homeJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.js'), 'utf8')
const homeWxml = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.wxml'), 'utf8')
const homeCss = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.wxss'), 'utf8')
const nginx = fs.readFileSync(path.resolve(root, '..', 'deploy', 'nginx.conf'), 'utf8')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_daily_todos') && migrate.includes('voice_text VARCHAR(1000)'), 'migration should create dated editable todos with narration text')
assert(route.includes("router.get('/'") && route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'") && route.includes("router.put('/admin/:id'") && route.includes("router.delete('/admin/:id'"), 'daily todo API should provide public reads and protected admin CRUD')
assert(route.includes("status='published'") && route.includes('todo_date=?'), 'public API should expose only published todos for the requested date')
assert(server.includes("app.use('/api/daily-todos'"), 'daily todo API should be mounted')
assert(nginx.includes('location ^~ /api/daily-todos/') && nginx.includes('location = /api/daily-todos'), 'Nginx should route public and admin todo requests to the community service')
assert(adminHtml.includes('data-view="todos"') && adminHtml.includes('id="todoPanel"') && adminHtml.includes('id="todoVoice"') && adminHtml.includes('/knowledge/todo-admin.js'), 'public admin should include today todo management and narration editing')
assert(adminJs.includes('/api/daily-todos') && adminJs.includes('todoFilterDate') && adminJs.includes('voice_text'), 'todo admin should filter by date and save narration text')
assert(homeJs.includes('/api/daily-todos?date=') && homeJs.includes('WechatSI.textToSpeech') && homeJs.includes('displayText: item.voiceText'), 'mini program home should load dated todos, display narration text and support speech')
assert(homeWxml.includes('今日待办') && homeWxml.includes('class="todo-voice-fab {{todoSpeaking') && homeWxml.includes('bindtap="toggleTodoSpeech"') && homeWxml.includes('class="todo-scroll"') && homeWxml.includes('{{item.displayText}}'), 'mini program home should keep a fixed card with an internally scrollable narration list and a bottom-right floating speech control')
assert(homeJs.includes('todoScrollable: estimatedHeight > 310') && homeWxml.includes("height:{{todoScrollable?'492rpx':'auto'}}") && homeWxml.includes('class="todo-scroll todo-list" style="height:auto"') && homeWxml.includes('<small wx:if="{{todoScrollable}}">'), 'today todo card should fit short content and only enable a capped internal scroller after reaching the content threshold')
assert(homeWxml.includes('class="todo-voice-inner"') && homeCss.includes('bottom:calc(126rpx + env(safe-area-inset-bottom))') && homeCss.includes('.todo-mic-head') && homeCss.includes('.todo-stop'), 'speech control should use a concentric circular microphone icon above the native tab bar and expose microphone/stop states')
assert(homeWxml.includes('<view class="todo-voice-fab') && !homeWxml.includes('wx:if="{{todos.length}}" class="todo-voice-fab') && homeWxml.includes('min-width:94rpx;max-width:94rpx;height:94rpx') && !homeWxml.includes('<button class="todo-voice-fab') && homeJs.includes('todosError'), 'floating speech control should remain visible without todos, distinguish loading failures, avoid native button sizing and force equal width and height')
assert(!homeJs.includes('daily_todo_done_') && !homeWxml.includes('已完成') && !homeWxml.includes('bindtap="toggleTodo"'), 'today todo should be informational and must not expose completion controls')

console.log('daily todo management tests passed')
