const assert = require('assert')
const fs = require('fs')
const path = require('path')

const communityRoot = path.resolve(__dirname, '..')
const projectRoot = path.resolve(communityRoot, '..')
const readCommunity = file => fs.readFileSync(path.join(communityRoot, file), 'utf8')
const readProject = file => fs.readFileSync(path.join(projectRoot, file), 'utf8')

const migration = readCommunity('db/migrate.js')
const route = readCommunity('routes/expert-studio.js')
const server = readCommunity('server.js')
const adminHtml = readCommunity('public/knowledge/policy-admin.html')
const adminJs = readCommunity('public/knowledge/expert-studio-admin.js')
const nginx = readProject('deploy/nginx.conf')
const publicRoute = readProject('cotton-app/server/routes/expert.js')
const adminRoute = readProject('cotton-app/server/routes/admin.js')
const platformAdmin = readProject('cotton-app/server/public/admin/dashboard.html')
const expertAdminRoute = readProject('cotton-app/server/routes/expert-admin.js')
const expertDashboard = readProject('cotton-app/server/public/expert/dashboard.html')
const miniJs = readProject('cotton-public/pages/expert/index.js')
const miniWxml = readProject('cotton-public/pages/expert/index.wxml')
const miniDetailJs = readProject('cotton-public/pages/expert/detail.js')
const miniDetailWxml = readProject('cotton-public/pages/expert/detail.wxml')
const websiteModule = readCommunity('public/site/public-modules.js')
const websiteStyles = readCommunity('public/site/styles.css')
const seed = readCommunity('db/expert_qa_seed.js')

assert(migration.includes('CREATE TABLE IF NOT EXISTS expert_contents'), 'community migration should ensure the shared expert content table exists')
assert(migration.includes("hasColumn('experts', 'avatar_url')") && migration.includes("hasColumn('expert_contents', 'is_featured')"), 'expert operations fields should migrate safely')
assert(migration.includes("hasColumn('expert_contents', 'source_key')") && migration.includes("require('./expert_qa_seed')"), 'curated Q&A should migrate idempotently with stable keys')
assert(migration.includes('community_seed_runs') && migration.includes('expert-qa-production-faq-v1'), 'curated Q&A seed batch should not return after an administrator deletes it')
for (const topic of ['播种适期', '出苗不齐', '棉苗发黄', '除草剂药害', '棉蚜', '红蜘蛛', '棉铃虫', '黄萎病', '脱叶催熟', '机采前']) {
  assert(seed.includes(topic), `curated expert Q&A is missing ${topic}`)
}
assert((seed.match(/key:/g) || []).length >= 14, 'first curated expert Q&A set should contain at least 14 entries')
assert(server.includes("app.use('/api/expert-studio'"), 'community server should mount expert studio API')
assert(nginx.includes('location ^~ /api/expert-studio/'), 'nginx should route expert studio APIs to community service')
assert(route.includes("router.post('/admin/upload'") && route.includes("router.post('/admin/experts'") && route.includes("router.post('/admin/contents'"), 'admin API should support images, experts and Q&A')
assert(route.includes('profile_only,sort_order,is_active) VALUES (?,?,?,?,?,?,?,?,?,0') && route.includes('passwordError(req.body.password)'), 'new online experts should receive real login accounts with strong passwords')
assert(route.includes("WHERE ec.type='qa'") && !route.includes("WHERE ec.type IN ('qa','video')"), 'expert studio APIs should only expose Q&A content')
assert(adminHtml.includes('data-view="experts"') && adminHtml.includes('精选问答') && adminHtml.includes('在线专家'), 'admin sidebar and two studio sections should be present')
assert(adminHtml.includes('studioExpertPhone') && adminHtml.includes('studioExpertPassword'), 'expert editor should collect login phone and password')
assert(adminJs.includes("$('studioExpertPhone')") && adminJs.includes('编辑/重置密码'), 'expert account UI should support login account editing and password resets')
assert(!adminHtml.includes('精选视频') && !adminHtml.includes('studioContentVideo'), 'admin UI should not expose video management')
assert(adminJs.includes("state = { tab: 'qa'") && !adminJs.includes('studioContentVideo'), 'admin UI should only switch between Q&A and experts')
assert(publicRoute.includes('ec.is_featured DESC') && publicRoute.includes('expertAvatarUrl'), 'public expert API should expose curated order and uploaded avatars')
assert(publicRoute.includes("qa: { label: '生产问答'") && !publicRoute.includes('问答课'), 'public expert API should not describe production Q&A as a course')
assert(miniJs.includes("activeLectureTab: 'qa'") && !miniJs.includes('videoContents'), 'mini program should only manage Q&A and expert tabs')
assert(miniWxml.includes('data-tab="qa"') && miniWxml.includes('data-tab="experts"') && !miniWxml.includes('data-tab="video"'), 'mini program should render only Q&A and expert navigation tabs')
assert(!miniWxml.includes('class="exp-ask"') && !miniWxml.includes('class="ask-banner"'), 'ask buttons must not appear before an online expert is selected')
assert(miniWxml.includes('wx:if="{{selectedExpert}}"') && miniWxml.includes('向TA提问'), 'the ask button should appear after selecting an online expert')
assert(miniJs.includes('selectedExpert: null') && miniJs.includes('expertId: expert.id'), 'question submission should carry the selected expert')
assert(publicRoute.includes('expert_id, expert_name') && publicRoute.includes('所选专家当前不在线'), 'question API should validate and store the selected expert')
assert(adminRoute.includes("router.post('/expert-accounts'") && adminRoute.includes("router.put('/expert-accounts/:id'") && adminRoute.includes("router.patch('/expert-accounts/:id/status'"), 'platform admin should manage expert login accounts')
assert(platformAdmin.includes('data-panel="expertAccounts"') && platformAdmin.includes('创建专家账号') && platformAdmin.includes('loadExpertAccounts'), 'platform admin expert-account UI is incomplete')
assert(expertAdminRoute.includes('WHERE expert_id=?') && expertAdminRoute.includes('WHERE id=? AND expert_id=?'), 'experts should only view and answer questions assigned to them')
assert(expertDashboard.includes('农户提问') && expertDashboard.includes('openReply'), 'expert dashboard should expose assigned questions and replies')
assert(expertAdminRoute.includes("router.get('/profile'") && expertAdminRoute.includes("router.put('/profile'") && expertAdminRoute.includes("router.patch('/password'"), 'expert self-service profile or password APIs are missing')
assert(expertAdminRoute.includes('bcrypt.compare(currentPassword') && expertAdminRoute.includes('validateStrongPassword(newPassword)'), 'expert password changes must verify the current password and enforce the strong-password policy')
assert(expertDashboard.includes('data-panel="profile"') && expertDashboard.includes('data-panel="security"') && expertDashboard.includes('saveProfile()') && expertDashboard.includes('changePassword()'), 'expert dashboard profile and account-security panels are incomplete')
assert(!miniWxml.includes('wx:else') && !miniWxml.includes('wx:elif'), 'expert page should avoid fragile adjacent conditional directives')
assert(miniDetailJs.includes("isQa: course.type === 'qa'") && miniDetailWxml.includes('class="faq-question"') && miniDetailWxml.includes('class="faq-answer"'), 'Q&A detail should use a dedicated question-and-answer presentation instead of the course template')
assert(!miniDetailJs.includes('ai_training_prompt') && !miniDetailWxml.includes('AI 陪练') && !miniDetailWxml.includes('<video'), 'expert detail should not expose AI training or video playback')
assert(!miniDetailWxml.includes('wx:else') && !miniDetailWxml.includes('wx:elif'), 'expert detail should avoid fragile adjacent conditional directives')
assert(websiteModule.includes('web-faq-question') && websiteModule.includes('web-faq-answer') && websiteStyles.includes('.web-faq-card'), 'website Q&A detail should match the dedicated question-and-answer presentation')
assert(!websiteModule.includes('精选视频') && !websiteModule.includes('expert-web-video'), 'public website should not expose expert videos')

console.log('expert studio management tests passed')
