const assert = require('assert')
const fs = require('fs')
const path = require('path')

const communityRoot = path.resolve(__dirname, '..')
const projectRoot = path.resolve(communityRoot, '..')
const readCommunity = file => fs.readFileSync(path.join(communityRoot, file), 'utf8')
const readProject = file => fs.readFileSync(path.join(projectRoot, file), 'utf8')

const migration = readCommunity('db/migrate.js')
const route = readCommunity('routes/expert-studio.js')
const server = readCommunity('server.js')
const adminHtml = readCommunity('public/knowledge/policy-admin.html')
const adminJs = readCommunity('public/knowledge/expert-studio-admin.js')
const nginx = readProject('deploy/nginx.conf')
const publicRoute = readProject('cotton-app/server/routes/expert.js')
const miniJs = readProject('cotton-public/pages/expert/index.js')
const miniWxml = readProject('cotton-public/pages/expert/index.wxml')

assert(migration.includes('CREATE TABLE IF NOT EXISTS expert_contents'), 'community migration should ensure the shared expert content table exists')
assert(migration.includes("hasColumn('experts', 'avatar_url')") && migration.includes("hasColumn('expert_contents', 'is_featured')"), 'expert operations fields should migrate safely')
assert(server.includes("app.use('/api/expert-studio'"), 'community server should mount expert studio API')
assert(nginx.includes('location ^~ /api/expert-studio/'), 'nginx should route expert studio APIs to community service')
assert(route.includes("router.post('/admin/upload'") && route.includes("router.post('/admin/experts'") && route.includes("router.post('/admin/contents'"), 'admin API should support media, experts, Q&A and videos')
assert(route.includes("WHERE ec.type IN ('qa','video')"), 'admin content list should be limited to the requested studio content types')
assert(adminHtml.includes('data-view="experts"') && adminHtml.includes('精选问答') && adminHtml.includes('在线专家') && adminHtml.includes('精选视频'), 'admin sidebar and three studio sections should be present')
assert(adminJs.includes("state = { tab: 'qa'") && adminJs.includes("uploadFile('studioContentVideoFile'"), 'admin UI should switch categories and upload videos')
assert(publicRoute.includes('ec.is_featured DESC') && publicRoute.includes('expertAvatarUrl'), 'public expert API should expose curated order and uploaded avatars')
assert(miniJs.includes("activeLectureTab: 'qa'") && miniJs.includes("courses.filter(item => item.type === 'video')"), 'mini program should split managed content into three columns')
assert(miniWxml.includes('data-tab="qa"') && miniWxml.includes('data-tab="experts"') && miniWxml.includes('data-tab="video"'), 'mini program should render all three navigation tabs')
assert(!miniWxml.includes('wx:else') && !miniWxml.includes('wx:elif'), 'expert page should avoid fragile adjacent conditional directives')

console.log('expert studio management tests passed')
