const assert = require('assert')
const fs = require('fs')
const path = require('path')

const communityRoot = path.resolve(__dirname, '..')
const projectRoot = path.resolve(communityRoot, '..')
const readCommunity = file => fs.readFileSync(path.join(communityRoot, file), 'utf8')
const readProject = file => fs.readFileSync(path.join(projectRoot, file), 'utf8')

const migration = readCommunity('db/migrate.js')
const route = readCommunity('routes/expert-studio.js')
const server = readCommunity('server.js')
const adminHtml = readCommunity('public/knowledge/policy-admin.html')
const adminJs = readCommunity('public/knowledge/expert-studio-admin.js')
const nginx = readProject('deploy/nginx.conf')
const publicRoute = readProject('cotton-app/server/routes/expert.js')
const miniJs = readProject('cotton-public/pages/expert/index.js')
const miniWxml = readProject('cotton-public/pages/expert/index.wxml')
const miniDetailJs = readProject('cotton-public/pages/expert/detail.js')
const miniDetailWxml = readProject('cotton-public/pages/expert/detail.wxml')
const websiteModule = readCommunity('public/site/public-modules.js')
const websiteStyles = readCommunity('public/site/styles.css')
const seed = readCommunity('db/expert_qa_seed.js')

assert(migration.includes('CREATE TABLE IF NOT EXISTS expert_contents'), 'community migration should ensure the shared expert content table exists')
assert(migration.includes("hasColumn('experts', 'avatar_url')") && migration.includes("hasColumn('expert_contents', 'is_featured')"), 'expert operations fields should migrate safely')
assert(migration.includes("hasColumn('expert_contents', 'source_key')") && migration.includes("require('./expert_qa_seed')"), 'curated Q&A should migrate idempotently with stable keys')
assert(migration.includes('community_seed_runs') && migration.includes('expert-qa-production-faq-v1'), 'curated Q&A seed batch should not return after an administrator deletes it')
for (const topic of ['播种适期', '出苗不齐', '棉苗发黄', '除草剂药害', '棉蚜', '红蜘蛛', '棉铃虫', '黄萎病', '脱叶催熟', '机采前']) {
  assert(seed.includes(topic), `curated expert Q&A is missing ${topic}`)
}
assert((seed.match(/key:/g) || []).length >= 14, 'first curated expert Q&A set should contain at least 14 entries')
assert(server.includes("app.use('/api/expert-studio'"), 'community server should mount expert studio API')
assert(nginx.includes('location ^~ /api/expert-studio/'), 'nginx should route expert studio APIs to community service')
assert(route.includes("router.post('/admin/upload'") && route.includes("router.post('/admin/experts'") && route.includes("router.post('/admin/contents'"), 'admin API should support media, experts, Q&A and videos')
assert(route.includes("WHERE ec.type IN ('qa','video')"), 'admin content list should be limited to the requested studio content types')
assert(adminHtml.includes('data-view="experts"') && adminHtml.includes('精选问答') && adminHtml.includes('在线专家') && adminHtml.includes('精选视频'), 'admin sidebar and three studio sections should be present')
assert(adminJs.includes("state = { tab: 'qa'") && adminJs.includes("uploadFile('studioContentVideoFile'"), 'admin UI should switch categories and upload videos')
assert(publicRoute.includes('ec.is_featured DESC') && publicRoute.includes('expertAvatarUrl'), 'public expert API should expose curated order and uploaded avatars')
assert(publicRoute.includes("qa: { label: '生产问答'") && !publicRoute.includes('问答课'), 'public expert API should not describe production Q&A as a course')
assert(miniJs.includes("activeLectureTab: 'qa'") && miniJs.includes("courses.filter(item => item.type === 'video')"), 'mini program should split managed content into three columns')
assert(miniWxml.includes('data-tab="qa"') && miniWxml.includes('data-tab="experts"') && miniWxml.includes('data-tab="video"'), 'mini program should render all three navigation tabs')
assert(!miniWxml.includes('wx:else') && !miniWxml.includes('wx:elif'), 'expert page should avoid fragile adjacent conditional directives')
assert(miniDetailJs.includes("isQa: course.type === 'qa'") && miniDetailWxml.includes('class="faq-question"') && miniDetailWxml.includes('class="faq-answer"'), 'Q&A detail should use a dedicated question-and-answer presentation instead of the course template')
assert(!miniDetailWxml.includes('wx:else') && !miniDetailWxml.includes('wx:elif'), 'expert detail should avoid fragile adjacent conditional directives')
assert(websiteModule.includes('web-faq-question') && websiteModule.includes('web-faq-answer') && websiteStyles.includes('.web-faq-card'), 'website Q&A detail should match the dedicated question-and-answer presentation')

console.log('expert studio management tests passed')
