const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '..')
const workspace = path.resolve(root, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const readWorkspace = file => fs.readFileSync(path.join(workspace, file), 'utf8')

const route = read('routes/pest-knowledge.js')
const migration = read('db/migrate.js')
const server = read('server.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/pest-admin.js')
const publicModules = read('public/site/public-modules.js')
const siteData = read('public/site/data.js')
const miniList = readWorkspace('cotton-public/pages/pest/index.js')
const miniDetail = readWorkspace('cotton-public/pages/pest/detail.js')
const pestCopy = readWorkspace('cotton-public/utils/pest-copy.js')
const home = readWorkspace('cotton-public/pages/index/index.wxml')
const my = readWorkspace('cotton-public/pages/my/index.js')
const nginx = readWorkspace('deploy/nginx.conf')

assert(migration.includes('CREATE TABLE IF NOT EXISTS community_pest_knowledge'), 'pest knowledge table migration is missing')
assert(server.includes("app.use('/api/pest-knowledge'"), 'pest knowledge route is not mounted')
assert(route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'") && route.includes("router.put('/admin/:id'"), 'pest admin CRUD routes are incomplete')
assert(route.includes("status='published'") && route.includes("router.get('/:id'"), 'published pest list/detail routes are incomplete')
assert(adminHtml.includes('data-view="pests"') && adminHtml.includes('id="pestPanel"') && adminHtml.includes('/knowledge/pest-admin.js'), 'admin pest module is not wired into the page')
assert(adminJs.includes('/api/pest-knowledge') && adminJs.includes('data-pest-edit') && adminJs.includes('data-pest-delete'), 'admin pest management behavior is incomplete')
assert(miniList.includes("'/api/pest-knowledge'") && miniDetail.includes('`/api/pest-knowledge/${this.pestId}`'), 'mini program pest pages must read the shared database API')
assert(publicModules.includes("pests: '/api/pest-knowledge'") && publicModules.includes('async function renderPests()'), 'public website pest pages must read the shared API')
assert(!siteData.includes('pests: ['), 'hardcoded website pest entries should be removed')
assert(!pestCopy.includes('棉蚜会聚集') && !pestCopy.includes("pests: ["), 'hardcoded mini program pest entries should be removed')
assert(!home.includes('未来三天持续高温，请及时关注地块墒情变化。'), 'hardcoded home reminder should be removed')
assert(my.includes("key === 'learning'") && my.includes("title: '正在开发中'"), 'my learning entry should show the developing notice')
assert(nginx.includes('location = /api/pest-knowledge') && nginx.includes('location ^~ /api/pest-knowledge/'), 'nginx pest API routes are missing')

console.log('pest-knowledge tests passed')
