const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const route = read('routes/plot-daily-work.js')
const migrate = read('db/migrate.js')
const server = read('server.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/farmer-land-admin.js')
const nginx = fs.readFileSync(path.resolve(root, '..', 'deploy', 'nginx.conf'), 'utf8')
const homeJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.js'), 'utf8')
const homeWxml = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.wxml'), 'utf8')
const appJson = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'app.json'), 'utf8')
const allTasksJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'daily-work', 'index.js'), 'utf8')
const allTasksWxml = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'daily-work', 'index.wxml'), 'utf8')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_plot_daily_work') && migrate.includes('FOREIGN KEY (plot_id) REFERENCES plots(id) ON DELETE CASCADE'), 'migration should create plot-scoped work with cascade cleanup')
assert(route.includes('router.get(\'/\', farmerAuth') && route.includes("payload.role !== 'farmer'"), 'public plot work must require a farmer token')
assert(route.includes('INNER JOIN plots p ON p.id=w.plot_id') && route.includes('p.user_id=?'), 'farmer query must enforce plot ownership in SQL')
assert(route.includes("w.status='published'") && route.includes('w.work_date=?'), 'farmer endpoint should return only published work for the requested date')
assert(route.includes("router.get('/admin/list', adminAuth") && route.includes("router.post('/admin', adminAuth") && route.includes("router.put('/admin/:id', adminAuth") && route.includes("router.delete('/admin/:id', adminAuth"), 'admin API should support complete maintenance')
assert(server.includes("app.use('/api/plot-daily-work'"), 'plot work API should be mounted')
assert(nginx.includes('location ^~ /api/plot-daily-work/') && nginx.includes('location = /api/plot-daily-work'), 'Nginx should route plot work requests to community service')
assert(adminHtml.includes('id="plotWorkModal"') && adminHtml.includes('id="plotWorkForm"') && adminJs.includes('data-plot-work') && adminJs.includes('/api/plot-daily-work'), 'plot management should provide per-plot work editing')
assert(homeJs.includes('loadPlotDailyWork()') && homeJs.includes('/api/plot-daily-work?date=') && homeWxml.includes('class="plot-work-section'), 'mini program home should load and render plot work')
assert(homeJs.includes('togglePlotWorkSpeech()') && homeWxml.includes('bindtap="togglePlotWorkSpeech"'), 'today farm work should retain the speech broadcast entry')
assert(!homeWxml.includes('今日提醒') && !homeWxml.includes('class="todo-section'), 'the removed standalone reminder module must not remain on the home page')
assert(homeWxml.includes('wx:for="{{plotWorkGroups}}"') && homeWxml.includes('{{item.plotName}}'), 'today farm work should be grouped by plot')
assert(homeWxml.includes('全部任务') && homeJs.includes("'/pages/daily-work/index'"), 'home page should link to the complete daily work page')
assert(appJson.includes('pages/daily-work/index') && allTasksJs.includes('/api/plot-daily-work?date=') && allTasksWxml.includes('按地块查看每日农事安排'), 'complete daily work page should be registered and load plot-scoped work')
assert(allTasksJs.includes('buildFarmWorkSpeech') && !allTasksJs.includes("'/api/voice-briefings/generate'"), 'complete daily work page speech should read only loaded farm work instead of reusing the home weather briefing')
assert(!allTasksWxml.includes('wx:else') && !allTasksWxml.includes('wx:elif'), 'complete daily work page should avoid fragile adjacent WXML conditional directives')

console.log('plot daily work tests passed')
