const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const route = read('routes/policies.js')
const migrate = read('db/migrate.js')
const auth = read('routes/auth.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/policy-admin.js')
const server = read('server.js')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_admins'), 'migration should create scoped community administrators')
assert(migrate.includes('CREATE TABLE IF NOT EXISTS policy_articles'), 'migration should create policy articles')
assert(auth.includes('signCommunityAdmin') && auth.includes("permission: account.permission_key"), 'community admin login should issue a scoped token')
assert(auth.includes("router.post('/admin/change-password'") && auth.includes('auth_version=auth_version+1'), 'community admins should be able to securely change and invalidate their password session')
assert(route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'") && route.includes("router.put('/admin/:id'"), 'policy management CRUD should exist')
assert(route.includes("router.post('/admin/change-password'") && route.includes('auth_version=auth_version+1'), 'the proven policy-admin API channel should support password changes')
assert(route.includes("status='published'") && route.includes("router.get('/:id'"), 'public policy API should expose published articles only')
assert(route.includes("'public_admin', 'policy_editor'"), 'policy API should accept the extensible public-admin scope')
assert(server.includes("app.use('/api/policies'"), 'policy API should be mounted')
assert(adminHtml.includes('Markdown 正文') && adminHtml.includes('实时预览'), 'policy editor should expose Markdown editing and preview')
assert(adminHtml.includes('class="sidebar"') && adminHtml.includes('class="topbar"'), 'public admin should share the core admin layout structure')
assert(adminHtml.includes('<span>政策中心</span>') && adminHtml.includes('<span>农户管理</span>') && !adminHtml.includes('商户审批'), 'public admin sidebar should expose policy and farmer management without merchant access')
assert(adminJs.includes('markdownHtml') && adminJs.includes("data-save"), 'policy editor should render previews and publish')
assert(adminHtml.includes('id="passwordForm"') && adminHtml.includes('data-view="security"'), 'public admin should expose account security in the shared sidebar layout')
assert(adminJs.includes("location.replace('/admin/login.html?role=admin')") && !adminJs.includes('/knowledge/admin-login.html'), 'logout should return to the unified admin login')
assert(server.includes("app.get('/knowledge/admin-login.html'") && server.includes("res.redirect(302, '/admin/login.html?role=admin')"), 'the obsolete login URL should redirect to unified login')
assert(adminHtml.includes('id="farmerPanel"') && adminHtml.includes('id="farmerModal"'), 'public admin should provide the shared farmer management interface')
assert(adminJs.includes("farmerApi('/farmers'") && adminJs.includes("/farmers/${id}/status"), 'public admin should load and manage farmers through scoped core APIs')

console.log('policy publishing tests passed')
