const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const route = read('routes/policies.js')
const migrate = read('db/migrate.js')
const auth = read('routes/auth.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/policy-admin.js')
const server = read('server.js')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_admins'), 'migration should create scoped community administrators')
assert(migrate.includes('CREATE TABLE IF NOT EXISTS policy_articles'), 'migration should create policy articles')
assert(auth.includes('signCommunityAdmin') && auth.includes("permission: account.permission_key"), 'community admin login should issue a scoped token')
assert(route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'") && route.includes("router.put('/admin/:id'"), 'policy management CRUD should exist')
assert(route.includes("status='published'") && route.includes("router.get('/:id'"), 'public policy API should expose published articles only')
assert(route.includes("'public_admin', 'policy_editor'"), 'policy API should accept the extensible public-admin scope')
assert(server.includes("app.use('/api/policies'"), 'policy API should be mounted')
assert(adminHtml.includes('Markdown 正文') && adminHtml.includes('实时预览'), 'policy editor should expose Markdown editing and preview')
assert(adminHtml.includes('class="sidebar"') && adminHtml.includes('class="topbar"'), 'public admin should share the core admin layout structure')
assert(adminHtml.includes('<span>政策中心</span>') && !adminHtml.includes('商户审批'), 'public admin sidebar should expose policy center only')
assert(adminJs.includes('markdownHtml') && adminJs.includes("data-save"), 'policy editor should render previews and publish')

console.log('policy publishing tests passed')
