const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const route = read('routes/policies.js')
const migrate = read('db/migrate.js')
const auth = read('routes/auth.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/policy-admin.js')
const farmerLandAdminJs = read('public/knowledge/farmer-land-admin.js')
const coreAdminRoute = read('../cotton-app/server/routes/admin.js')
const server = read('server.js')
const serviceProductRoute = read('routes/service-products.js')
const miniProgramPolicyIndex = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'policy', 'index.wxml'), 'utf8')
const miniProgramPolicyJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'policy', 'index.js'), 'utf8')
const miniProgramHomeJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.js'), 'utf8')
const miniProgramHomeWxml = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.wxml'), 'utf8')
const miniProgramAppWxss = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'app.wxss'), 'utf8')
const miniProgramPolicyDetailWxml = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'policy', 'detail.wxml'), 'utf8')
const miniProgramPolicyDetailWxss = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'policy', 'detail.wxss'), 'utf8')
const miniProgramPolicyDetailJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'policy', 'detail.js'), 'utf8')
const miniProgramMarkdown = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'utils', 'markdown.js'), 'utf8')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_admins'), 'migration should create scoped community administrators')
assert(migrate.includes('CREATE TABLE IF NOT EXISTS policy_articles'), 'migration should create policy articles')
assert(migrate.includes("hasColumn('policy_articles', 'source_published_at')") && migrate.includes('source_published_at DATETIME'), 'migration should preserve the original source publication time independently')
assert(migrate.includes("hasColumn('policy_articles', 'content_type')") && migrate.includes('idx_policy_content_type'), 'migration should add the compatible policy/news content type')
assert(migrate.includes("hasColumn('policy_articles', 'is_home_featured')") && migrate.includes('idx_policy_home'), 'migration should add independent homepage curation fields')
assert(migrate.includes("status='published' AND is_featured=1") && migrate.includes('legacyFeatured.length'), 'first migration should preserve up to five legacy featured articles on the homepage')
assert(migrate.includes('CREATE TABLE IF NOT EXISTS policy_comments'), 'migration should create article comments')
assert(migrate.includes("hasColumn('policy_comments', 'parent_id')") && migrate.includes('CREATE TABLE IF NOT EXISTS policy_comment_likes'), 'comments should support threaded replies and per-user likes')
assert(auth.includes('signCommunityAdmin') && auth.includes("permission: account.permission_key"), 'community admin login should issue a scoped token')
assert(auth.includes("router.post('/admin/change-password'") && auth.includes('auth_version=auth_version+1'), 'community admins should be able to securely change and invalidate their password session')
assert(route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'") && route.includes("router.put('/admin/:id'"), 'policy management CRUD should exist')
assert(route.includes("router.post('/admin/change-password'") && route.includes('auth_version=auth_version+1'), 'the proven policy-admin API channel should support password changes')
assert(route.includes("status='published'") && route.includes("router.get('/:id'"), 'public policy API should expose published articles only')
assert(route.includes("['policy', 'industry', 'finance', 'home'].includes(req.query.type)") && route.includes('contentType'), 'public content API should support policy, industry, finance and homepage-only articles')
assert(route.includes('coverImage: row.cover_url || (imageMatch') && route.includes('body_markdown'), 'public content list should prefer the managed cover and fall back to the first Markdown image')
assert(miniProgramPolicyJs.includes("name: '政策中心'") && miniProgramPolicyJs.includes("name: '行业资讯'") && miniProgramPolicyJs.includes("['国家', '自治区', '地区', '县级']") && miniProgramPolicyJs.includes("['产业', '农机', '农资', '市场', '气象']"), 'the mini program policy entry should define the requested two-level categories')
assert(miniProgramPolicyJs.includes('item.contentType === this.data.activeType') && miniProgramPolicyJs.includes('item.section === this.data.activeSection'), 'article feed should strictly match both selected tab levels')
assert(miniProgramPolicyIndex.includes('primary-tabs') && miniProgramPolicyIndex.includes('secondary-tabs') && miniProgramPolicyIndex.includes('activeSection') && miniProgramPolicyIndex.includes('class="feed"') && !miniProgramPolicyIndex.includes('group-card'), 'the mini program policy entry should render the requested two-level tab feed instead of overview cards')
assert(!miniProgramPolicyIndex.includes('<scroll-view class="secondary-tabs"'), 'secondary policy tabs should use a fixed-height flex row that remains visible on real devices')
assert(route.includes("router.get('/:id/comments'") && route.includes("router.post('/:id/comments'") && route.includes('评论发送太频繁'), 'article detail should provide public comments and protected publishing')
assert(route.includes("router.post('/:id/comments/:commentId/like'") && route.includes('policy_comment_likes') && route.includes('parent_id'), 'comment APIs should provide replies and toggleable likes')
assert(route.includes("'public_admin', 'policy_editor'"), 'policy API should accept the extensible public-admin scope')
assert(server.includes("app.use('/api/policies'"), 'policy API should be mounted')
assert(server.includes("app.use('/api/service-products'"), 'service product catalog API should be mounted')
assert(serviceProductRoute.includes("status='published'") && serviceProductRoute.includes("router.get('/admin/list'") && serviceProductRoute.includes("router.post('/admin'"), 'service product API should separate public published products from protected admin CRUD')
assert(adminHtml.includes('Markdown 正文') && adminHtml.includes('实时预览'), 'policy editor should expose Markdown editing and preview')
assert(adminHtml.includes('id="sourcePublishedAt"') && adminJs.includes('source_published_at') && route.includes('sourcePublishedAt'), 'policy publishing should manage and expose the original publication time')
assert(adminHtml.includes('class="sidebar"') && adminHtml.includes('class="topbar"'), 'public admin should share the core admin layout structure')
assert(adminHtml.includes('<span>政策资讯</span>') && adminHtml.includes('<span>农户管理</span>') && adminHtml.includes('<span>地块管理</span>') && !adminHtml.includes('商户审批'), 'public admin sidebar should expose separate farmer and plot management without merchant access')
assert(adminHtml.includes('<span>农机服务</span>') && adminHtml.includes('<span>农资服务</span>') && adminHtml.includes('/knowledge/product-admin.js'), 'public admin sidebar should expose independent machinery and supplies catalog management')
assert(adminJs.includes('markdownHtml') && adminJs.includes("data-save"), 'policy editor should render previews and publish')
assert(adminHtml.includes('id="contentType"') && adminHtml.includes('id="section"') && adminJs.includes("industry:['产业','农机','农资','市场','气象']"), 'admin editor should classify policy and industry content, including agricultural inputs')
assert(route.includes("new Set(['产业', '农机', '农资', '市场', '气象'])"), 'policy API should accept the agricultural-input industry section')
assert(route.includes("router.patch('/admin/:id/home-featured'") && route.includes('首页最多推送5篇文章') && route.includes("req.query.homepage"), 'policy API should support a five-article homepage curation queue')
assert(adminJs.includes('data-home=') && adminJs.includes('is_home_featured') && adminHtml.includes('最多同时推送 5 篇'), 'admin should expose homepage push controls')
assert(miniProgramHomeJs.includes("'/api/policies?homepage=1'") && miniProgramHomeJs.includes("item.contentType === 'finance'") && !miniProgramHomeJs.includes('棉花生产支持政策要点'), 'mini program homepage should load and route unified curated articles instead of hard-coded news')
assert(miniProgramHomeWxml.includes('<text>首页推送</text>') && !miniProgramHomeWxml.includes('精选政策、行业与公共服务内容') && !miniProgramHomeWxml.includes('<text>棉花资讯</text>'), 'homepage should present the curated content area as a concise 首页推送 heading')
assert(miniProgramAppWxss.includes('font-size: 24rpx;') && miniProgramAppWxss.includes('line-height: 1.5;'), 'mini program should provide a readable global type baseline')
assert(miniProgramPolicyDetailWxml.includes('class="action-group"') && miniProgramPolicyDetailWxss.includes('flex:0 0 252rpx') && miniProgramPolicyDetailWxss.includes('button.action::after'), 'article comment, collect and share actions should use a fixed right group and override native button spacing')
assert(miniProgramPolicyDetailWxml.includes('bindtap="startReply"') && miniProgramPolicyDetailWxml.includes('bindtap="toggleCommentLike"') && miniProgramPolicyDetailWxml.includes("{{replyTargetId?'写下回复…':'欢迎发表评论'}}"), 'article comments should expose an inline send bar, replies and likes')
assert(!miniProgramHomeWxml.includes('作业 · 检修 · 调度') && !miniProgramHomeWxml.includes('种子 · 肥料 · 植保') && !miniProgramHomeWxml.includes('轧花 · 检测 · 仓储'), 'homepage service entries should avoid redundant helper captions')
assert(adminHtml.includes('id="markdownFile"') && adminJs.includes('new FileReader()'), 'admin editor should import local Markdown files before preview and publish')
assert(miniProgramPolicyDetailJs.includes('{ indentParagraphs: true }') && miniProgramMarkdown.includes("textNode('\\u3000\\u3000')"), 'policy prose should use a two-character first-line indent without indenting headings or lists')
assert(!adminHtml.includes('id="summary"') && route.includes('generatedSummary'), 'article publishing should derive internal search text instead of asking editors for a summary')
assert(adminHtml.includes('<span>优棉金融</span>') && adminHtml.includes('<span>首页推送</span>') && adminHtml.includes('/knowledge/content-admin.js'), 'public admin should expose finance articles and a unified homepage curation workbench')
assert(migrate.includes("content_type='finance'") && migrate.includes('finance article created'), 'migration should seed one editable article for every finance topic')
assert(adminHtml.includes('id="passwordForm"') && adminHtml.includes('data-view="security"'), 'public admin should expose account security in the shared sidebar layout')
assert(adminJs.includes("location.replace('/admin/login.html?role=admin')") && !adminJs.includes('/knowledge/admin-login.html'), 'logout should return to the unified admin login')
assert(server.includes("app.get('/knowledge/admin-login.html'") && server.includes("res.redirect(302, '/admin/login.html?role=admin')"), 'the obsolete login URL should redirect to unified login')
assert(adminHtml.includes('id="farmerPanel"') && adminHtml.includes('id="farmerModal"'), 'public admin should provide the shared farmer management interface')
assert(adminJs.includes("farmerApi('/farmers'") && adminJs.includes("/farmers/${id}/status"), 'public admin should load and manage farmers through scoped core APIs')
assert(adminHtml.includes('id="farmerAccountTable"') && adminHtml.includes('id="plotPanel"') && adminHtml.includes('id="plotDetailModal"') && adminHtml.includes('id="countyStats"') && adminHtml.includes('id="riskHeat"'), 'admin should separate farmer accounts from plot map, county statistics and weather risk views')
assert(farmerLandAdminJs.includes("/api/admin/farmer-landscape") && farmerLandAdminJs.includes('phoneMasked') && farmerLandAdminJs.includes('plotMapCanvas'), 'farmer-land admin should load privacy-preserving aggregate data and render plot geometry')
assert(coreAdminRoute.includes("router.get('/farmer-landscape'") && coreAdminRoute.includes('maskFarmerPhone') && coreAdminRoute.includes('weather_observations') && coreAdminRoute.includes('highWindAvailable: false'), 'core API should aggregate farmers, plots, production and available weather observations without inventing wind alerts')

console.log('policy publishing tests passed')
