const assert = require('assert')
const fs = require('fs')
const path = require('path')

const communityRoot = path.resolve(__dirname, '..')
const miniRoot = path.resolve(communityRoot, '..', 'cotton-public')
const readCommunity = file => fs.readFileSync(path.join(communityRoot, file), 'utf8')
const readMini = file => fs.readFileSync(path.join(miniRoot, file), 'utf8')
const app = JSON.parse(readMini('app.json'))
const migrate = readCommunity('db/migrate.js')
const route = readCommunity('routes/processing-factories.js')
const server = readCommunity('server.js')
const nginx = fs.readFileSync(path.resolve(communityRoot, '..', 'deploy/nginx.conf'), 'utf8')
const adminHtml = readCommunity('public/knowledge/policy-admin.html')
const adminJs = readCommunity('public/knowledge/factory-admin.js')
const data = readMini('utils/processing-data.js')
const indexJs = readMini('pages/production/index.js')
const indexWxml = readMini('pages/production/index.wxml')
const detailJs = readMini('pages/production/detail.js')
const detailWxml = readMini('pages/production/detail.wxml')

assert(app.pages.includes('pages/production/index') && app.pages.includes('pages/production/detail'), 'processing list and detail pages should be registered')
assert(data.includes("id: 'ginning'") && data.includes("id: 'testing'") && data.includes("id: 'storage'"), 'processing module should retain fixed ginning, testing and storage concepts')
assert(!data.includes('const FACTORIES') && !data.includes('factoryById'), 'factory records must not remain hard-coded in the mini program')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_processing_factories'), 'migration should create processing factory table')
for (const field of ['longitude', 'latitude', 'annual_capacity_tons', 'manager_name', 'contact_phone', 'image_urls_json']) {
  assert(migrate.includes(field), `factory table should include ${field}`)
}
assert(migrate.includes("'653165263'") && migrate.includes("'653165060'") && migrate.includes("'653165395'"), 'verified initial factory points should seed the database')
assert(route.includes("WHERE status='published'") && route.includes("router.get('/admin/list'") && route.includes("router.post('/admin'"), 'API should separate public published data and authenticated administration')
assert(route.includes("router.put('/admin/:id'") && route.includes("router.delete('/admin/:id'"), 'admin API should provide update and delete operations')
assert(server.includes("app.use('/api/processing-factories'"), 'community server should mount factory routes')
assert(nginx.includes('location ^~ /api/processing-factories/'), 'nginx should proxy processing factory APIs')

assert(adminHtml.includes('data-view="factories"') && adminHtml.includes('id="factoryPanel"') && adminHtml.includes('id="factoryLongitude"') && adminHtml.includes('id="factoryImages"'), 'admin should expose factory CRUD fields')
assert(adminJs.includes("'/admin/list'") && adminJs.includes('data-factory-edit') && adminJs.includes('data-factory-delete'), 'admin interface should list, edit and delete factory records')
assert(indexJs.includes("auth.request('GET', '/api/processing-factories')") && detailJs.includes('`/api/processing-factories/${this.factoryId}`'), 'mini program list and detail must load factories from the API')
assert(indexJs.includes('markersOf') && indexJs.includes('openMarker') && indexWxml.includes('<map'), 'processing entry should wire map markers to dynamic factory details')
assert(detailJs.includes('wx.openLocation') && detailJs.includes('wx.makePhoneCall'), 'factory detail should support map navigation and published telephone contact')
assert(detailWxml.includes('年加工产能') && detailWxml.includes('factory.managerText') && detailWxml.includes('factory.imageUrls'), 'factory detail should display managed capacity, manager and image fields')
assert(!indexWxml.includes('wx:else') && !detailWxml.includes('wx:else'), 'processing WXML should avoid fragile wx:else chains on real devices')

console.log('processing service database and mini program tests passed')
