const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const migrate = read('db/migrate.js')
const route = read('routes/service-products.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/product-admin.js')
const miniRoot = path.resolve(root, '..', 'cotton-public')
const machineryJs = fs.readFileSync(path.join(miniRoot, 'pages/machinery/index.js'), 'utf8')
const machineryWxml = fs.readFileSync(path.join(miniRoot, 'pages/machinery/index.wxml'), 'utf8')
const suppliesJs = fs.readFileSync(path.join(miniRoot, 'pages/supplies/index.js'), 'utf8')
const suppliesWxml = fs.readFileSync(path.join(miniRoot, 'pages/supplies/index.wxml'), 'utf8')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_service_products'), 'migration should create an isolated public service product catalog')
assert(migrate.includes("ENUM('machinery','supplies')") && migrate.includes("ENUM('draft','published','offline')"), 'catalog should separate product types and publishing states')
assert(route.includes("machinery: new Set(['耕整地', '播种铺膜', '田间管理', '采收运输'])"), 'machinery categories should be allowlisted')
assert(route.includes("supplies: new Set(['种子', '肥料', '农药', '地膜'])"), 'supplies categories should be allowlisted')
assert(route.includes("WHERE service_type=? AND status='published'"), 'mini program must only receive published catalog products')
assert(route.includes('productAdminAuth') && route.includes("router.patch('/admin/:id/status'"), 'catalog mutations should require admin auth and support listing control')
assert(adminHtml.includes('data-product-type="machinery"') && adminHtml.includes('data-product-type="supplies"'), 'admin should expose separate machinery and supplies menus')
assert(adminJs.includes("categories =") && adminJs.includes("status === 'published' ? '已上架'"), 'admin should classify and manage listing states')
assert(machineryJs.includes('/api/service-products?type=machinery') && machineryJs.includes("{ id: '采收运输'"), 'machinery page should load the managed machinery catalog')
assert(suppliesJs.includes('/api/service-products?type=supplies') && suppliesJs.includes("{ id: '地膜'"), 'supplies page should load the managed supplies catalog')
assert(machineryWxml.includes('item.intro') && machineryWxml.includes('item.features') && suppliesWxml.includes('item.intro') && suppliesWxml.includes('item.features'), 'product cards should display introductions and features')
assert(!machineryWxml.includes('.slice(') && !suppliesWxml.includes('.slice('), 'real-device WXML should avoid method calls in bindings')

console.log('service product catalog tests passed')
