const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const route = read('routes/voice-briefings.js')
const migrate = read('db/migrate.js')
const server = read('server.js')
const adminHtml = read('public/knowledge/policy-admin.html')
const adminJs = read('public/knowledge/voice-admin.js')
const nginx = fs.readFileSync(path.resolve(root, '..', 'deploy', 'nginx.conf'), 'utf8')
const homeJs = fs.readFileSync(path.resolve(root, '..', 'cotton-public', 'pages', 'index', 'index.js'), 'utf8')
const regionWeather = require('../utils/region-weather')

assert(migrate.includes('CREATE TABLE IF NOT EXISTS community_voice_briefings') && migrate.includes('uniq_voice_briefing_user_date'), 'migration should create one briefing per farmer and date')
assert(server.includes("app.use('/api/voice-briefings'"), 'voice briefing route should be mounted')
assert(nginx.includes('location ^~ /api/voice-briefings/') && nginx.includes('location = /api/voice-briefings'), 'Nginx should route briefing requests to community service')
assert(route.includes('const DAILY_GENERATION_LIMIT = 100') && route.includes('const FARMER_CACHE_TTL_MS = 2 * 60 * 60 * 1000') && route.includes("router.post('/generate', farmerAuth") && route.includes('farmerGenerationJobs'), 'farmers should generate on demand with a two-hour cache and duplicate-request lock')
assert(route.includes('INNER JOIN farmers f ON f.user_id=u.id') && !route.includes("WHERE id=? AND role=? LIMIT 1"), 'farmer authorization must use the farmer profile instead of the legacy primary role')
assert(adminJs.includes('const DAILY_GENERATION_LIMIT = 100') && adminHtml.includes('每天每位农户最多生成 100 次'), 'admin UI should display the same daily generation limit as the API')
assert(!route.includes("router.post('/admin/generate-all'") && !adminHtml.includes('id="batchGenerateVoiceBtn"') && !adminJs.includes("request('/admin/generate-all'"), 'the retired admin batch generation entry should be removed')
assert(route.includes("router.put('/admin/:userId', adminAuth") && route.includes("router.get('/today', farmerAuth"), 'briefings should support manual review, publish and farmer retrieval')
assert(route.includes("status='published'") && route.includes('saveFarmerGeneratedBriefing') && route.includes('generationContextHash(context)'), 'farmer-generated content should be persisted, published, and keyed by its generation context')
assert(route.includes('严禁编造天气') && route.includes('最近一次真实观测'), 'AI prompt must prohibit invented weather and agronomy data')
assert(route.includes('60至120个汉字') && route.includes('天气讲完后再按地块播报今日农事') && route.includes('不寒暄、不铺垫、不重复'), 'AI prompt should produce concise weather-first briefings')
assert(route.includes('singlePromptData(context)') && route.includes('weatherSource=current_location') && route.includes('不得说“暂无天气”'), 'AI prompt must distinguish current-location weather from registered-region fallback weather')
assert(route.includes('fetchCurrentLocationWeather') && route.includes("source: 'current_location'") && route.includes('registered_location_fallback'), 'farmer playback should prefer current phone location and fall back to the registered region')
assert(homeJs.includes('latitude: position.latitude') && homeJs.includes('longitude: position.longitude'), 'the mini program should pass current coordinates only when the farmer requests playback')
assert.strictEqual(regionWeather.resolveWeatherRegion('').name, '莎车县', 'empty registered region should use Shache County')
assert.strictEqual(regionWeather.resolveWeatherRegion('新疆喀什地区巴楚县阿瓦提镇').name, '巴楚县', 'registered county text should resolve to its county weather center')
assert.strictEqual(regionWeather.resolveWeatherRegion('莎车').name, '莎车县', 'county names without suffix should resolve when commonly entered')
assert(adminHtml.includes('data-view="voice"') && adminHtml.includes('id="generateVoiceBtn"') && adminHtml.includes('id="voiceContent"'), 'admin UI should expose explicit generation and manual editing')
assert(adminJs.includes("request('/admin/generate'") && adminJs.includes("save('draft')") && adminJs.includes("save('published')"), 'admin editor should generate, save draft and publish')
assert(homeJs.includes("auth.request('POST', '/api/voice-briefings/generate'") && !homeJs.includes('/api/voice-briefings/admin/generate'), 'mini program should request farmer-scoped generation without calling an admin endpoint')

console.log('smart voice briefing tests passed')
