const assert = require('assert')
const fs = require('fs')
const path = require('path')

const rootDir = path.join(__dirname, '..', '..')

function readRootFile(...parts) {
  return fs.readFileSync(path.join(rootDir, ...parts), 'utf8')
}

function run() {
  const appJson = JSON.parse(readRootFile('app.json'))
  assert.strictEqual(appJson.plugins.WechatSI.provider, 'wx069ba97219f66d99')
  assert.strictEqual(appJson.plugins.WechatSI.version, '0.3.7')
  assert.ok(appJson.permission['scope.record'].desc.includes('语音'))

  const aiPage = readRootFile('pages', 'ai', 'index.js')
  const aiWxml = readRootFile('pages', 'ai', 'index.wxml')
  assert.ok(aiPage.includes("requirePlugin('WechatSI')"))
  assert.ok(aiPage.includes("speechManager.start({ duration: 60000, lang: 'zh_CN' })"))
  assert.ok(aiPage.includes('_stopSpeechPlayback()'))
  assert.ok(aiPage.includes('recordingStarting'))
  assert.ok(aiPage.includes('recognizing'))
  assert.ok(aiPage.includes('voiceAnswerEnabled'))
  assert.ok(aiPage.includes('speakingMessageId'))
  assert.ok(aiPage.includes('wx.setInnerAudioOption'))
  assert.ok(aiPage.includes('obeyMuteSwitch: false'))
  assert.ok(aiPage.includes('mixWithOther: false'))
  assert.ok(aiPage.includes('this._audio.volume = 1'))
  assert.ok(aiPage.includes('_voiceTouchActive'))
  assert.ok(aiPage.includes('_voiceStopRequested'))
  assert.ok(aiPage.includes('_voiceResultHandled'))
  assert.ok(aiPage.includes('_voiceTimeoutNotified'))
  assert.ok(aiPage.includes('_speechActuallyStarted'))
  assert.ok(aiPage.includes('_voicePendingStop'))
  assert.ok(aiPage.includes('_voiceAuthorizeTimer'))
  assert.ok(aiPage.includes('_voiceStartTimer'))
  assert.ok(aiPage.includes('_lastRecognizedText'))
  assert.ok(aiPage.includes('const VOICE_RESULT_TIMEOUT_MS = 12000'))
  assert.ok(aiPage.includes('const VOICE_START_TIMEOUT_MS = 6000'))
  assert.ok(aiPage.includes('const VOICE_AUTHORIZE_TIMEOUT_MS = 8000'))
  assert.ok(aiPage.includes('voiceReadyAgain'))
  assert.ok(aiPage.includes('voiceRecognizing'))
  assert.ok(aiPage.includes('voiceRecognizeTimeout'))
  assert.ok(aiPage.includes('!this._voiceTouchActive'))
  assert.ok(aiPage.includes('onHide()'))
  assert.ok(aiPage.includes('onToggleVoiceAnswer'))
  assert.ok(aiPage.includes('onReplayAnswer'))
  assert.ok(aiPage.includes('speakable'))
  assert.ok(aiPage.includes('options.fromVoice || this.data.voiceAnswerEnabled'))
  assert.ok(aiPage.includes('_stopSpeechRecord'))
  assert.ok(aiPage.includes('_requestRecordPermission'))
  assert.ok(aiPage.includes('_authorizeRecordPermission'))
  assert.ok(aiPage.includes('_bindSpeechCallback'))
  assert.ok(aiPage.includes('speechManager[name] = handler'))
  assert.ok(aiPage.includes('_appendVoiceFailure'))
  assert.ok(aiPage.includes('_formatVoiceError'))
  assert.ok(aiPage.includes('_armVoiceAuthorizeGuard'))
  assert.ok(aiPage.includes('_clearVoiceAuthorizeGuard'))
  assert.ok(aiPage.includes('_armVoiceStartGuard'))
  assert.ok(aiPage.includes('_clearVoiceStartGuard'))
  assert.ok(aiPage.includes('_sendVoiceText'))
  assert.ok(aiPage.includes('if (!text && timedOut)'))
  assert.ok(aiPage.includes('if (this.data.recordingStarting && !this._speechActuallyStarted)'))
  assert.ok(aiPage.includes('wx.getSetting'))
  assert.ok(aiPage.includes("authSetting['scope.record']"))
  assert.ok(aiPage.includes('stage:'))
  assert.ok(aiPage.includes('reason:'))
  assert.ok(aiPage.includes('code:'))
  assert.ok(aiPage.includes('麦克风权限检查超时'))
  assert.ok(aiPage.includes('微信语音插件启动超时'))
  assert.ok(aiPage.includes('等待识别结果超时'))
  assert.ok(aiPage.includes('onVoiceGlobalEnd'))
  assert.ok(aiPage.includes('onVoiceTapFallback'))
  assert.ok(aiWxml.includes('bindtouchend="onVoiceGlobalEnd"'))
  assert.ok(aiWxml.includes('bindtouchcancel="onVoiceGlobalCancel"'))
  assert.ok(aiWxml.includes('bindtouchstart="onVoiceStart"'))
  assert.ok(aiWxml.includes('bindtouchend="onVoiceEnd"'))
  assert.ok(aiWxml.includes('bindtouchcancel="onVoiceCancel"'))
  assert.ok(aiWxml.includes('bindtap="onVoiceTapFallback"'))
  assert.ok(aiWxml.includes('voice-answer-toggle'))
  assert.ok(aiWxml.includes('bindtap="onToggleVoiceAnswer"'))
  assert.ok(aiWxml.includes('bindtap="onReplayAnswer"'))
  assert.ok(aiWxml.includes('data-id="{{item.id}}"'))
  assert.ok(aiWxml.includes('copy.voiceAnswer'))
  assert.ok(aiWxml.includes('copy.replayAnswer'))
  assert.ok(aiWxml.includes('recognizing ? copy.voiceRecognizing'))
  assert.ok(aiWxml.includes('recording || recordingStarting || recognizing'))
  assert.ok(!aiWxml.includes('catchtouchend="onVoiceEnd"'))

  console.log('miniapp voice config tests passed')
}

run()
